name: TD-MMock
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test for TD
    steps:
      - uses: actions/checkout@v2
      - name: Test for cwe 242 and 676
        id: hello
        uses: mmock-uni/td_action@v4
